### PR TITLE
feature_pointing_device_modes QMK PR suggestions

### PR DESCRIPTION
**Pull request by JohSchneider**
some possible improvements/suggestions for the PR into QMK
= commits to cherry-pick through :-)

i'm "looking through&playing with" the code, to see if the cirque-trackpad-dpad mode/feature i have in mind could fit and possibly be added into this one

### CODE REVIEW

**Comment by JohSchneider** [comment]
@Alabastard 
>  included there but I'm wary about the changes to the cirque code as that seems a bit out of scope.

yes, those are WIP... and can be disregarded -> cherry pick what you thing fits the scope (-:

when you go over my refactoring commit... maybe consider re-refactoring: some of the resulting names are a bit clunky and sometimes not fully consistent with the rest (e.g. "point device mode" vs "pointing mode", pluras vs singular "mode"/"modes", etc)

**Comment by JohSchneider** [comment]
question: are the `POINTING_MODE_DEVICE_MODES_INVERT_X` and Y actually needed?
since there already is a `POINTING_DEVICE_INVERT_X` and even code to handle device rotation
from reading through the code it probably is enough to run the mouse_report_t through `pointing_device_adjust_by_defines` at "the right places"

**Comment by JohSchneider** [comment]
Okay, this [30fd47f](https://github.com/Alabastard/qmk_firmware/pull/2/commits/30fd47f8f2d890d1f690dfe8c939152f6bf56772)
is basically the feature i was after: with a cirque touchpad, internally in absolute coordinate mode, it is possible to categorize touch events into virtual keys; the main difference to the current code are:
1. keys are held as long as touchDown=true
2. diagonals: possibility to hold two adjacent keys
3. there is a layer-synchronized keymap (similar to the encoders)

with the later the pointing_device_mode becomes orthogonal to the keymap; e.g. a user can switch the pointing device into some mode, and have the keymap cycle through others

TODO: documentation :-), and the keymap `pointing_device_mode_maps` feature could be merged in/replaced by the `pointing_virtkey_map`

thoughts?

**Comment by JohSchneider** [comment]
> question: are the `POINTING_MODE_DEVICE_MODES_INVERT_X` and Y actually needed? since there already is a `POINTING_DEVICE_INVERT_X` and even code to handle device rotation from reading through the code it probably is enough to run the mouse_report_t through `pointing_device_adjust_by_defines` at "the right places"

with [14c2f04](https://github.com/Alabastard/qmk_firmware/pull/2/commits/14c2f04acc4b27b1b88ae6a5bfb14467687df3da) fixing the up/down - i think the additional inversion defines can be dropped - since the movement direction and cursor/scroll/... directions now map in all modes: PM_NONE, PRECISION. DRAG and CARET

**Comment by JohSchneider** [comment]
@Alabastard the last two refactorings are bigger ones, but reduce the overall codesize/complexity - which should help in getting things merged
as far as i can tell the "basic feature scope" still works as intended - please test on your end :-)

**Comment by Alabastard** [comment]
> question: are the `POINTING_MODE_DEVICE_MODES_INVERT_X` and Y actually needed? since there already is a `POINTING_DEVICE_INVERT_X` and even code to handle device rotation from reading through the code it probably is enough to run the mouse_report_t through `pointing_device_adjust_by_defines` at "the right places"

Interesting...
As this has come up before I tried to minimize the amount of code I touched in the existing code base (which admittedly can lead to some bloat).  I would need to test this and ensure that it could do what I normally use this for (inverting most modes Y axis while not inverting mouse Y axis as that feels more comfortable for me).

> @Alabastard the last two refactorings are bigger ones, but reduce the overall codesize/complexity - which should help in getting things merged
> as far as i can tell the "basic feature scope" still works as intended - please test on your end :-)

I finally have some time to start reviewing this.

I do like the idea of code size and/or complexity reduction as I was already feeling it was getting quite bloated and was looking for ways to slim it down but I was struggling with keeping all the intended components of the feature and mirroring structure of existing features.

I'll comment again once I have finished my review (but feel free to continue working on it),  Thanks again for putting in this work!

**Comment by Alabastard** [comment]
Alright so I have had some time to go through this and while I'm not sure about all of the changes here is a summary:

**100% Agree:**
1. Homogenization of the defines.
2. Removal of some of bloat where I was getting too "cute" with AVR optimization.
3. A negative `mouse_report.y` is in fact an "upward" vector in the context of the screen coordinate system so direction naming should reflect that. _silly that I did not confirm this before moving ahead, thanks._
4.  Adding the capability to allow for d-pad like control is a good idea but I would not want this to be the default (most of the modes I use would be annoying to have diagonal multi-presses so this should be enabled on a mode by mode basis).
5. The typo's... _goodness gracious there were more than I thought thanks for catching them I will need to do a through code review once I finalize_

**Things I need to think more about:**
1. Conditional branches inside of a loop is best avoided if possible as this can be slow on AVR and will noticeably impact response times for the pointing device movement to button press. _Curious what platform you are testing on (an RP2040 would have no issues here I imagine)_
2. Having mode x and y as local variables removes the need for the device pointing mode struct and you can stick with arrays as you have done here, however this would get messy when you have multiple devices using pointing modes at the same time all reporting to the same master so I do think the x and y for modes should be tracked per device. _but maybe everything else should just be an array_
3. Having pointing modes work in tandem with layers can be done already with just a bit of layer state code and having a whole additional matrix row taken up to add this niche feature seems excessive to me.

Will add more as I go through the review...
Thank you so much for all the work you did here!!
I will refactor my code and clean it up you have given me a lot of ideas on how things should be improved.
Would like to talk to you about the d-pad style diagonal multi-press more once I get there as I realize that could be a nice add.

**Comment by JohSchneider** [comment]
>  Thank you so much for all the work you did here!!

you're welcome :-)

>4 , Adding the capability to allow for d-pad like control is a good idea but I would not want this to be the default (most of the modes I use would be annoying to have diagonal multi-presses so this should be enabled on a mode by mode basis).

that's why i left the quadrant-categorization in there as well, the quadrant/octant split could be a boolean switch in the function, and then have it only 'on' for some modes
splitting into just two fields could also make sense; some of the example keymaps only set left/right keys, and up/down as KC_NO - which effectively creates a deadzone there; might or might not be desirable... :-)

> Would like to talk to you about the d-pad style diagonal multi-press more once I get there as I realize that could be a nice add.

mostly for actual "direction pad" related things = cursor keys where it is a usecase to hit two keys at the same time for diagonal movement (dpad -> gamecontrollers)

> 2, Having mode x and y as local variables removes the need for the device pointing mode struct and you can stick with arrays as you have done here, however this would get messy when you have multiple devices using pointing modes at the same time all reporting to the same master so I do think the x and y for modes should be tracked per device. but maybe everything else should just be an array

i would question if there truly are "multiple devices ... at the same time", e.g. more than one device generating mouse_reports that need to be processed so quickly that the "overflow" from previous events would interfere; isn't it more like "burst of events from one device;; short pause; burst of events from another"?

> 3. Having pointing modes work in tandem with layers can be done already with just a bit of layer state code and having a whole additional matrix row taken up to add this niche feature seems excessive to me.

i would also merge the two keymaps midterm... i ended up with them since a) layer synchronization vs mode-state and b) tapping out keys vs holding keys.
what might simplify the usage scenario (and with that code size): separate the key-press functions from the cursor-movments, remove some predefined modes. giving the user the choice between 
- a PM_PRECISION: influence the cursor with multipliers
- PM_DRAG: remap cursor axis
- PM_KEY_TAP: look up keymap and tap out keys
- PM_KEY_HOLD: look up keymap and hold/release keys

the predefined PM_CARET, PM_VOLUME, ... would be removed/moved to examples for the keymaps
to further reduce code complexity the whole "define your own mode" could be removed, if the predefined modes already cover the most common usecases

looking at the encoder feature - which also syncs with the keyboards layer state - how about this:
|layer | pm_key_map | pm_mode|
|---|---|---|
[Base] | KC_NO... | PM_NORMAL |
|[Raise] | caret-keys | PM_KEY_HOLD| 
|[lower] | volume keys | PM_KEY_TAP |
|[special] | history keys | PM_KEY_TAP|

the current mode too is layer synchronized, but remembered/switchable with a keycode - e.g. while in the [Base] layer hit a key to switch to PM_DRAG, then PM_PREC and cycle back to PM_NORMAL, or when in [Raise] toggle between PM_KEY_TAP and PM_KEY_HOLD 
my guess here is that most users will have one mode per layer and not bother switching them in the orthogonal direction = stay on the same layer but switch different pm_modes (since it is harder to remember/get used to)

**Comment by Alabastard** [comment]
Sorry for not responding earlier. I can work on this in earnest now.

>that's why i left the quadrant-categorization in there as well, the quadrant/octant split could be a boolean switch in the function, and then have it only 'on' for some modes
>splitting into just two fields could also make sense; some of the example keymaps only set left/right keys, and up/down as KC_NO - which effectively creates a deadzone there; might or might not be desirable... :-)

I see your point here and I was kind of thinking along the same lines after I posted my initial response that it depends on how keypresses are resolved as being below the threshold could mean no keys are pressed (but it is only half a bit to have a Null so likely that could be the simplest approach).  Also yeah I was thinking that it would be a per mode setting to describe if it would be two, four, eight, or D-PAD (eight would not work well for trackballs IMO but could work for track pads maybe?).

>i would question if there truly are "multiple devices ... at the same time", e.g. more than one device generating mouse_reports that need to be processed so quickly that the "overflow" from previous events would interfere; isn't it more like "burst of events from one device;; short pause; burst of events from another"?

This is a very good point and I wasn't thinking about it this way.  You could be correct here in practice, but unfortunately this would require testing to see how it impacts the feel of trackballs as they are surprisingly finicky and it is easier than you might think to "feel" or notice small changes in how the code handles things (part of the reason I was chasing AVR optimisations so much). This could impact track pads as well but maybe not as drastically, would be good to know before comitting anything.
Unfortunately I only know of one person running two trackballs right now and I haven't talked with them in a while and it will be a while before I finish designing my two trackball keyboard.

I think the safest decision would be to leave x, and y as device independent until this could be thoroughly tested but this could unfortunately be a waste of resources in the meantime (waste only really matters for AVR as RP2040's and most ARM chips likely have plenty of ram for this)

_Small note here: often dual trackballs or trackpads are used by those using cad software and they will likely be using them simultaneously so my thinking is we would need to test how that feels resolving these ignoring count differences between devices or tracking them independently (this also will be hardware and threshold dependent)_

>the current mode too is layer synchronized, but remembered/switchable with a keycode - e.g. while in the [Base] layer hit a key to switch to PM_DRAG, then PM_PREC and cycle back to PM_NORMAL, or when in [Raise] toggle between PM_KEY_TAP and PM_KEY_HOLD
my guess here is that most users will have one mode per layer and not bother switching them in the orthogonal direction = stay on the same layer but switch different pm_modes (since it is harder to remember/get used to)

Hmmm this is interesting and a bit of a departure from how I originally envisioned and used the modes.  I originally was thinking that I should allow for switching between layer-synced (basically handled like encoders) or not for the maps but I like the idea of this being a thing handled by selecting a mode type as it were and this being done either layer synced or not I think this would allow for more simple and easier to understand customisation.


>the predefined PM_CARET, PM_VOLUME, ... would be removed/moved to examples for the keymaps
to further reduce code complexity the whole "define your own mode" could be removed, if the predefined modes already cover the most common use cases

I agree that these two in particular are somewhat niche and have been thinking for a while they might be better off relegated to the docs as part of example uses of key press rather than built in taking up code space.

Also I completely missed the press and hold behavior! Does this work with track pads? is the x,y sent by the track pad depend on location so as long as your finger is in a position on the pad you could be over a threshold?
_This makes me realise that I have been so focused on how trackballs work (as that is what I have) that I have been overlooking how the modes would work with other pointing devices_

I will work on this over the next couple days I have a page of notes of ideas/issues from your PR and our conversation (I should give you some credit in the code here as even if I don't accept the PR and write it all myself you have really contributed here).

Once I upload again I'll probably bug you for your opinion and input (sorry in advance ha ha)

**Comment by JohSchneider** [comment]
> Also I completely missed the press and hold behavior! Does this work with track pads? is the x,y sent by the track pad depend on location so as long as your finger is in a position on the pad you could be over a threshold? _This makes me realise that I have been so focused on how trackballs work (as that is what I have) that I have been overlooking how the modes would work with other pointing devices_
> 

the cirque trackpad i have here is relatively different to the other pointing devices: these trackpads can operate in absolute mode, which then reports x/y/z of touch events internally, with z being the proximity to the pad. with that it is possible to have events for a x/y position see z "fall" towards zero, and below a threshold it is registered as "touch down" - if one manages to stay perfectly still (which is unlikely) the device internally still generates events in the configured intervall; until z goes up above a threshold -> "touch down" is released.
so basically one big button you can click ;-)
the qmk sensor driver takes those absolute values and converts them to relative mouse reports - e.g. if one manages to stay perfectly still, the trackpad still continues tracking - but no mouse reports are sent since the delta is zero

other pointing devices = most/all of them act as mice do: sending bursts of relative coordinates upon movement
the other exception would be analog joysticks, which just deflect in two directions 

> I will work on this over the next couple days I have a page of notes of ideas/issues from your PR and our conversation (I should give you some credit in the code here as even if I don't accept the PR and write it all myself you have really contributed here).
> 

already curious what direction the code/feature will take (-:

> Once I upload again I'll probably bug you for your opinion and input (sorry in advance ha ha)

 hehe, go ahead :-)

**Comment by Alabastard** [comment]
Well I'll put this here to keep a record of my progress:
### Small doc changes:
- [x] Homogenise defines
- [ ] Homogenise function names
- [x] Trim default modes to just Precision and Drag scroll and add others to docs
- [ ] Clean up code and remove overzealous optimisation
- [ ] Add Layer sync functionality (will work like encoders with mode types as additional way to have pointing modes)
### Big Doc changes:
- [ ] Add press and hold behaviour possibility (this needs more planning)
- [ ] Add diagonal direction detection 
- [ ] Add two button press logic for diagonals (D-Pad functionality)
- [ ] Make device data and mode tracking and access more consistent

I'll keep this updated as I go I'll submit an update to the repo once I make sufficient progress and it compiles

**Comment by Alabastard** [comment]
>the cirque trackpad i have here is relatively different to the other pointing devices: these trackpads can operate in absolute mode, which then reports x/y/z of touch events internally, with z being the proximity to the pad. with that it is possible to have events for a x/y position see z "fall" towards zero, and below a threshold it is registered as "touch down" - if one manages to stay perfectly still (which is unlikely) the device internally still generates events in the configured intervall; until z goes up above a threshold -> "touch down" is released.

Hmm I would need to have a think on how to handle the press and hold behaviour I'm thinking:
1. Hold would be initiated by pointing movement being above a threshold
2. Hold is kept until threshold is met again in another direction or custom additional condition (such as touch down release for track pads)

Would this be a good start or do you see issues with this?
_I feel as if this approach would be difficult to work with trackballs without a very high threshold which would be dpi dependent which is why I didn't think to include it originally... but cirque pads are very popular and should be taken into consideration_

**Comment by JohSchneider** [comment]
> Would this be a good start or do you see issues with this?

how is the 'met again in another direction' differentiated from an intentional "key press" in that direction?
this way the trackball would need to be rolled left;right to get a "virtual button left", but then a right;left to quickly follow up with a "virtual button right" is not easily possible

>  _I feel as if this approach would be difficult to work with trackballs without a very high threshold which would be dpi dependent which is why I didn't think to include it originally... but cirque pads are very popular and should be taken into consideration_

follow the `get_virtual_key_state` through the pointing_device_driver, adding per device type implementations could be the easy way out; joysticks would work with their deadzone around the neutral/center position and as long as the deflection is in one direction the virtual key is held
for trackballs (or any other device that only creates the usual mouse-reports with x/y delta: tracking a time-delta and direction could work: 
 1 a user rolls the ball in one direction however slowly which starts the "button down",
 2 literally lets go, at which point the reports stop to come in
 3 a timeout is reached and the "button up" is sent

the current implementation that taps out keys and consumes the accumulated x/y can be thought of as a vector that is dragged from the center, and "chipped away" towards the center with each tap.
a hold&release would still drag said vector, but have it snap back to center after the dragging stopped + timout

**Comment by Alabastard** [comment]
Alright getting close here:
- [x] Rename functions
- [x] Eliminate redundant functions
- [x] Trim down to just drag scroll as the only built in mode
- [x] Precision is now handled as a per device setting and will affect all modes on that device
- [x] Add precision step and max settings
    - _Minimum is always one don't know if I should set up changing that_
- [x] Add keys for dynamically stepping through precision as well as enable/disable
    - _I am thinking this should be a setting such as `POINTING_MODES_ENABLE_DYNAMIC_PRECISION` otherwise it will just default to the max or step__
- [x] remove divisor post processing
    - _it was really only needed to allow precision mode to affect all other modes_
- [x] Consolidate all device dependent and dynamic variables to a struct and have only one array of this struct
    - _This is maybe a little less runtime efficient but it simplifies coding quite a bit_
- [x] Update new direction determining function to handle diagonal and neutral positions
    - _This I think will based on the current mode's divisor if you are over the threshold it will send the press does that make sense to you?_

**Pull request closed without merging**
